package com.pinova.service.impl;
import com.baomidou.mybatisplus.core.toolkit.*;import com.pinova.common.error.BusinessException;import com.pinova.mapper.*;import com.pinova.pojo.entity.*;import com.pinova.service.*;import com.pinova.service.command.*;import com.pinova.service.error.AdminCatalogErrorCode;import com.pinova.service.model.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service public class AdminCategoryServiceImpl implements AdminCategoryService{
 private final ProductCategoryMapper categories;private final ProductSpuMapper products;private final AdminAuthorizationService auth;private final AdminOperationAuditService audit;
 public AdminCategoryServiceImpl(ProductCategoryMapper c,ProductSpuMapper p,AdminAuthorizationService a,AdminOperationAuditService d){categories=c;products=p;auth=a;audit=d;}
 @Override @Transactional(readOnly=true) public List<AdminCategoryResult> list(AuthenticatedAdminResult a){auth.requireSuperAdmin(a);return categories.selectList(Wrappers.lambdaQuery(ProductCategory.class).orderByAsc(ProductCategory::getLevel).orderByAsc(ProductCategory::getSortOrder).orderByAsc(ProductCategory::getId)).stream().map(AdminCategoryServiceImpl::result).toList();}
 @Override @Transactional public AdminCategoryResult save(SaveAdminCategoryCommand c){auth.requireSuperAdmin(c==null?null:c.admin());validate(c);List<ProductCategory> all=categories.selectList(Wrappers.lambdaQuery(ProductCategory.class).orderByAsc(ProductCategory::getId).last("FOR UPDATE"));Map<Long,ProductCategory> byId=new HashMap<>();all.forEach(v->byId.put(v.getId(),v));ProductCategory parent=c.parentId()==null?null:byId.get(c.parentId());if(c.parentId()!=null&&parent==null)notFound();short newLevel=(short)(parent==null?1:parent.getLevel()+1);Instant now=Instant.now();
  if(c.id()==null){if(newLevel>5)depth();ProductCategory v=new ProductCategory();v.setId(IdWorker.getId());v.setParentId(c.parentId());v.setCategoryCode(c.categoryCode().trim().toLowerCase(Locale.ROOT));v.setName(c.name().trim());v.setLevel(newLevel);v.setSortOrder(c.sortOrder());v.setIconUrl(norm(c.iconUrl()));v.setStatus(c.status());v.setVersion(0);v.setDeleted(false);v.setCreatedAt(now);v.setCreatedBy(c.admin().id());v.setUpdatedAt(now);v.setUpdatedBy(c.admin().id());categories.insert(v);record(c.admin().id(),"CREATE",v.getId(),null);return result(v);}
  ProductCategory current=byId.get(c.id());if(current==null)notFound();if(!c.version().equals(current.getVersion()))conflict();Set<Long> descendants=descendants(all,current.getId());if(c.parentId()!=null&&(c.parentId().equals(current.getId())||descendants.contains(c.parentId())))throw new BusinessException(AdminCatalogErrorCode.CATEGORY_CYCLE);int delta=newLevel-current.getLevel();int max=all.stream().filter(v->descendants.contains(v.getId())).mapToInt(ProductCategory::getLevel).max().orElse(current.getLevel());if(max+delta>5||newLevel<1)depth();
  int n=categories.update(null,Wrappers.lambdaUpdate(ProductCategory.class).eq(ProductCategory::getId,current.getId()).eq(ProductCategory::getVersion,current.getVersion()).set(ProductCategory::getParentId,c.parentId()).set(ProductCategory::getName,c.name().trim()).set(ProductCategory::getSortOrder,c.sortOrder()).set(ProductCategory::getIconUrl,norm(c.iconUrl())).set(ProductCategory::getStatus,c.status()).set(ProductCategory::getLevel,newLevel).set(ProductCategory::getUpdatedAt,now).set(ProductCategory::getUpdatedBy,c.admin().id()).setSql("version = version + 1"));if(n!=1)conflict();
  if(delta!=0)for(ProductCategory child:all)if(descendants.contains(child.getId())){int u=categories.update(null,Wrappers.lambdaUpdate(ProductCategory.class).eq(ProductCategory::getId,child.getId()).eq(ProductCategory::getVersion,child.getVersion()).set(ProductCategory::getLevel,(short)(child.getLevel()+delta)).set(ProductCategory::getUpdatedAt,now).set(ProductCategory::getUpdatedBy,c.admin().id()).setSql("version = version + 1"));if(u!=1)conflict();}
  record(c.admin().id(),"UPDATE",current.getId(),null);return result(categories.selectById(current.getId()));}
 @Override @Transactional public void delete(AuthenticatedAdminResult a,Long id,int version,String reason){auth.requireSuperAdmin(a);if(id==null||id<=0||reason==null||reason.isBlank())invalid();ProductCategory c=categories.selectOne(Wrappers.lambdaQuery(ProductCategory.class).eq(ProductCategory::getId,id).last("FOR UPDATE"));if(c==null)notFound();if(categories.selectCount(Wrappers.lambdaQuery(ProductCategory.class).eq(ProductCategory::getParentId,id))>0||products.selectCount(Wrappers.lambdaQuery(ProductSpu.class).eq(ProductSpu::getCategoryId,id))>0)throw new BusinessException(AdminCatalogErrorCode.CATEGORY_NOT_EMPTY);Instant now=Instant.now();int n=categories.update(null,Wrappers.lambdaUpdate(ProductCategory.class).eq(ProductCategory::getId,id).eq(ProductCategory::getVersion,version).set(ProductCategory::getDeleted,true).set(ProductCategory::getDeletedAt,now).set(ProductCategory::getDeletedBy,a.id()).set(ProductCategory::getUpdatedAt,now).set(ProductCategory::getUpdatedBy,a.id()).setSql("version = version + 1"));if(n!=1)conflict();record(a.id(),"DELETE",id,reason);}
 private void record(Long op,String action,Long id,String reason){audit.record(new RecordAdminAuditCommand(op,"CATEGORY",action,"PRODUCT_CATEGORY",String.valueOf(id),null,norm(reason),null,null));}
 private static Set<Long> descendants(List<ProductCategory> all,Long root){Set<Long> ids=new HashSet<>();boolean changed;do{changed=false;for(ProductCategory c:all)if(c.getParentId()!=null&&(c.getParentId().equals(root)||ids.contains(c.getParentId()))&&ids.add(c.getId()))changed=true;}while(changed);return ids;}
 private static void validate(SaveAdminCategoryCommand c){if(c==null||c.categoryCode()==null||!c.categoryCode().trim().matches("^[a-zA-Z][a-zA-Z0-9_-]{1,63}$")||c.name()==null||c.name().isBlank()||c.name().trim().length()>64||c.sortOrder()==null||c.sortOrder()<0||c.status()==null||(c.status()!=0&&c.status()!=1)||(c.id()!=null&&(c.version()==null||c.version()<0)))invalid();}
 private static AdminCategoryResult result(ProductCategory c){return new AdminCategoryResult(c.getId(),c.getParentId(),c.getCategoryCode(),c.getName(),c.getLevel(),c.getSortOrder(),c.getIconUrl(),c.getStatus(),c.getVersion());}private static String norm(String v){return v==null||v.isBlank()?null:v.trim();}private static void invalid(){throw new BusinessException(AdminCatalogErrorCode.INVALID);}private static void notFound(){throw new BusinessException(AdminCatalogErrorCode.CATEGORY_NOT_FOUND);}private static void conflict(){throw new BusinessException(AdminCatalogErrorCode.CATEGORY_CONFLICT);}private static void depth(){throw new BusinessException(AdminCatalogErrorCode.CATEGORY_DEPTH);}
}
