package com.pinova.service.impl;
import com.baomidou.mybatisplus.core.toolkit.Wrappers;import com.pinova.common.error.*;import com.pinova.mapper.*;import com.pinova.pojo.entity.*;import com.pinova.service.*;import com.pinova.service.command.RecordAdminAuditCommand;import com.pinova.service.model.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.List;
@Service public class AdminMemberServiceImpl implements AdminMemberService {
    private final MemberAccountMapper members;private final MemberLoginSessionMapper sessions;private final AdminAuthorizationService auth;private final AdminOperationAuditService audit;
    public AdminMemberServiceImpl(MemberAccountMapper m,MemberLoginSessionMapper s,AdminAuthorizationService a,AdminOperationAuditService d){members=m;sessions=s;auth=a;audit=d;}
    @Override @Transactional(readOnly=true) public List<AdminMemberResult> list(AuthenticatedAdminResult admin,String keyword,Short status){auth.requireSuperAdmin(admin);var q=Wrappers.lambdaQuery(MemberAccount.class).eq(status!=null,MemberAccount::getStatus,status).and(keyword!=null&&!keyword.isBlank(),w->w.like(MemberAccount::getMemberNo,keyword.trim()).or().like(MemberAccount::getUsername,keyword.trim()).or().like(MemberAccount::getNickname,keyword.trim())).orderByDesc(MemberAccount::getCreatedAt).last("LIMIT 200");return members.selectList(q).stream().map(AdminMemberServiceImpl::result).toList();}
    @Override @Transactional(readOnly=true) public AdminMemberResult get(AuthenticatedAdminResult admin,String no){auth.requireSuperAdmin(admin);return result(require(no,false));}
    @Override @Transactional public AdminMemberResult changeStatus(AuthenticatedAdminResult admin,String no,int version,short status,String reason){auth.requireSuperAdmin(admin);if((status!=0&&status!=1)||reason==null||reason.isBlank())throw new BusinessException(CommonErrorCode.INVALID_REQUEST,"会员状态或原因无效");MemberAccount m=require(no,true);Instant now=Instant.now();int n=members.update(null,Wrappers.lambdaUpdate(MemberAccount.class).eq(MemberAccount::getId,m.getId()).eq(MemberAccount::getVersion,version).set(MemberAccount::getStatus,status).set(MemberAccount::getUpdatedAt,now).set(MemberAccount::getUpdatedBy,admin.id()).setSql("version = version + 1"));if(n!=1)throw new BusinessException(CommonErrorCode.INVALID_REQUEST,"会员状态已变化，请刷新后重试");if(status==0)revoke(m.getId(),admin.id(),now);audit.record(new RecordAdminAuditCommand(admin.id(),"MEMBER",status==0?"DISABLE":"ENABLE","MEMBER_ACCOUNT",no,null,reason.trim(),null,null));return result(require(no,false));}
    @Override @Transactional public void revokeSessions(AuthenticatedAdminResult admin,String no,String reason){auth.requireSuperAdmin(admin);if(reason==null||reason.isBlank())throw new BusinessException(CommonErrorCode.INVALID_REQUEST,"必须填写下线原因");MemberAccount m=require(no,true);revoke(m.getId(),admin.id(),Instant.now());audit.record(new RecordAdminAuditCommand(admin.id(),"MEMBER","REVOKE_SESSIONS","MEMBER_ACCOUNT",no,null,reason.trim(),null,null));}
    private void revoke(Long id,Long op,Instant now){sessions.update(null,Wrappers.lambdaUpdate(MemberLoginSession.class).eq(MemberLoginSession::getMemberId,id).isNull(MemberLoginSession::getRevokedAt).set(MemberLoginSession::getRevokedAt,now).set(MemberLoginSession::getUpdatedAt,now).set(MemberLoginSession::getUpdatedBy,op));}
    private MemberAccount require(String no,boolean lock){if(no==null||no.isBlank())throw new BusinessException(CommonErrorCode.INVALID_REQUEST,"会员不存在");var q=Wrappers.lambdaQuery(MemberAccount.class).eq(MemberAccount::getMemberNo,no.trim());if(lock)q.last("FOR UPDATE");MemberAccount m=members.selectOne(q);if(m==null)throw new BusinessException(CommonErrorCode.INVALID_REQUEST,"会员不存在");return m;}
    private static AdminMemberResult result(MemberAccount m){return new AdminMemberResult(m.getId(),m.getMemberNo(),m.getUsername(),m.getMobile(),m.getEmail(),m.getNickname(),m.getAvatarUrl(),m.getStatus(),m.getVersion(),m.getLastLoginAt(),m.getCreatedAt());}
}
