package com.pinova.api.controller;
import com.fasterxml.jackson.databind.ObjectMapper;import com.pinova.api.assembler.AdminProductResponseAssembler;import com.pinova.api.media.MinioMediaStorage;import com.pinova.api.request.*;import com.pinova.api.response.*;import com.pinova.api.web.CurrentAdminResolver;import com.pinova.common.api.ApiResponse;import com.pinova.service.AdminProductService;import com.pinova.service.command.*;import com.pinova.service.model.*;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.List;
@RestController @RequestMapping("/admin/products") public class AdminProductController{
 private final AdminProductService service;private final CurrentAdminResolver resolver;private final AdminProductResponseAssembler assembler;private final ObjectMapper json;private final MinioMediaStorage storage;
 public AdminProductController(AdminProductService s,CurrentAdminResolver r,AdminProductResponseAssembler a,ObjectMapper j,MinioMediaStorage m){service=s;resolver=r;assembler=a;json=j;storage=m;}
 @GetMapping public ApiResponse<List<AdminProductResponse>> list(HttpServletRequest r){return ApiResponse.success(service.list(resolver.requireCurrentAdmin(r)).stream().map(assembler::toResponse).toList());}
 @GetMapping("/{id}") public ApiResponse<AdminProductResponse> get(@PathVariable Long id,HttpServletRequest r){return ApiResponse.success(assembler.toResponse(service.get(resolver.requireCurrentAdmin(r),id)));}
 @PostMapping public ApiResponse<AdminProductResponse> create(@Valid @RequestBody SaveAdminProductRequest b,HttpServletRequest r){return ApiResponse.success(assembler.toResponse(service.saveProduct(product(resolver.requireCurrentAdmin(r),null,b))));}
 @PutMapping("/{id}") public ApiResponse<AdminProductResponse> update(@PathVariable Long id,@Valid @RequestBody SaveAdminProductRequest b,HttpServletRequest r){return ApiResponse.success(assembler.toResponse(service.saveProduct(product(resolver.requireCurrentAdmin(r),id,b))));}
 @PostMapping("/{id}/skus") public ApiResponse<AdminProductResponse> createSku(@PathVariable Long id,@Valid @RequestBody SaveAdminSkuRequest b,HttpServletRequest r){return ApiResponse.success(assembler.toResponse(service.saveSku(sku(resolver.requireCurrentAdmin(r),id,null,b))));}
 @PutMapping("/{id}/skus/{skuId}") public ApiResponse<AdminProductResponse> updateSku(@PathVariable Long id,@PathVariable Long skuId,@Valid @RequestBody SaveAdminSkuRequest b,HttpServletRequest r){return ApiResponse.success(assembler.toResponse(service.saveSku(sku(resolver.requireCurrentAdmin(r),id,skuId,b))));}
 @PutMapping("/{id}/detail") public ApiResponse<AdminProductResponse> detail(@PathVariable Long id,@Valid @RequestBody SaveAdminProductDetailRequest b,HttpServletRequest r)throws Exception{return ApiResponse.success(assembler.toResponse(service.saveDetail(new SaveAdminProductDetailCommand(resolver.requireCurrentAdmin(r),id,json.writeValueAsString(b.document()),b.packingList(),b.usageInstructions(),b.afterSalesNote(),b.version()))));}
 @DeleteMapping("/{id}") public ApiResponse<Void> delete(@PathVariable Long id,@RequestParam int version,@Valid @RequestBody AdminReasonRequest b,HttpServletRequest r){service.deleteProduct(resolver.requireCurrentAdmin(r),id,version,b.reason());return ApiResponse.success(null);}
 @DeleteMapping("/{id}/skus/{skuId}") public ApiResponse<Void> deleteSku(@PathVariable Long id,@PathVariable Long skuId,@RequestParam int version,@Valid @RequestBody AdminReasonRequest b,HttpServletRequest r){service.deleteSku(resolver.requireCurrentAdmin(r),id,skuId,version,b.reason());return ApiResponse.success(null);}
 @PostMapping(value="/{id}/media",consumes="multipart/form-data") public ApiResponse<AdminProductResponse> media(@PathVariable Long id,@RequestPart MultipartFile file,@RequestParam(required=false)Long skuId,@RequestParam Short mediaRole,@RequestParam(defaultValue="0")Integer sortOrder,@RequestParam(required=false)String altText,HttpServletRequest r){AuthenticatedAdminResult admin=resolver.requireCurrentAdmin(r);var uploaded=storage.upload(id,file);return ApiResponse.success(assembler.toResponse(service.addMedia(new AddAdminProductMediaCommand(admin,id,skuId,uploaded.objectKey(),uploaded.mimeType(),uploaded.fileSizeBytes(),null,null,mediaRole,altText,sortOrder))));}
 @DeleteMapping("/{id}/media/{mediaId}") public ApiResponse<Void> deleteMedia(@PathVariable Long id,@PathVariable Long mediaId,@RequestParam int version,@Valid @RequestBody AdminReasonRequest b,HttpServletRequest r){service.deleteMedia(resolver.requireCurrentAdmin(r),id,mediaId,version,b.reason());return ApiResponse.success(null);}
 private static SaveAdminProductCommand product(AuthenticatedAdminResult a,Long id,SaveAdminProductRequest b){return new SaveAdminProductCommand(a,id,b.shopId(),b.categoryId(),b.spuCode(),b.name(),b.summary(),b.mainImageKey(),b.status(),b.sortOrder(),b.version());}private static SaveAdminSkuCommand sku(AuthenticatedAdminResult a,Long p,Long id,SaveAdminSkuRequest b){return new SaveAdminSkuCommand(a,p,id,b.skuCode(),b.specSummary(),b.salePriceFen(),b.inventoryMode(),b.mainImageKey(),b.barcode(),b.status(),b.sortOrder(),b.version());}}
